### PR TITLE
DSA most important topics in javascripts

### PR DESCRIPTION
**Pull request by rahulgithub-web**
**Added DSA most important topics in javascripts**

These topics are asked in most of the interviews.

### CODE REVIEW

**Comment by rahulgithub-web** [comment]
@rahulgithub-web **hacktoberfest-accepted**

**Comment by rahulgithub-web** [comment]
HACKTOBERFEST-ACCEPTED

**Comment by typhonshambo** [comment]
It's just an empty folder :(

**Comment by rahulgithub-web** [comment]
Sorry for the mistake Now I have uploaded all the files successfully

**Comment by typhonshambo** [comment]
Waaaooo Awesome work!

**Pull request merged**
