### PR TITLE
Three sum program

### PR DESCRIPTION
**Pull request by shubhambaghel34**
added code for Find a triplet that sum to a given value

### CODE REVIEW

**Comment by shubhambaghel34** [comment]
@typhonshambo I am facing this issue while pulling the repo
image

**Comment by UlissesJunior** [comment]
Why do you change my factorial code? 😥

**Comment by shubhambaghel34** [comment]
> Why do you change my factorial code? 😥

Hey buddy @UlissesJunior  I have mentioned screenshot above where it showing such error where I haven't added anything its just taking pull,Although after that I am seeing that file changed at my local end even though unstaging it its not getting undo
Please let me know if anything I can do

**Comment by UlissesJunior** [comment]
No problem guy @shubhambaghel34,
I saw that the file returned to normal (I think).

**Comment by shubhambaghel34** [comment]
> 

ok thanks, sounds cool @UlissesJunior

**Pull request merged**
